config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users
    root 'articles#index'

    resources :articles do
      resources :comments, only: %i[create destroy]
    end

    resources :categories, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }

  delegate :name, to: :category, prefix: true
  delegate :email, to: :user, prefix: true

  paginates_per 10

  scope :desc_order, -> { order(created_at: :desc) }
  scope :without_highlights, ->(ids) { where("id NOT IN(#{ids})") if ids.present? }
  scope :filter_by_category, ->(category) { where category_id: category.id if category.present? }
  scope :filter_by_archive, lambda { |month_year|
    if month_year
      date = Date.strptime(month_year, '%B %Y')
      where created_at: date.beginning_of_month..date.end_of_month.next_day
    end
  }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :restrict_with_error

  validates :name,
            presence: true,
            length: { minimum: 3 },
            uniqueness: { case_sensitive: false }

  scope :sorted, -> { order(:name) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true

  delegate :email, to: :user, prefix: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, and :omniauthable

  devise :confirmable,
         :database_authenticatable,
         :recoverable,
         :registerable,
         :rememberable,
         :trackable,
         :validatable

  validate :password_complexity

  private

  def password_complexity
    return if password.nil?

    errors.add :password, :complexity unless CheckPasswordComplexityService.call(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  around_action :switch_locale

  private

  def default_url_options
    { locale: I18n.locale }
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore

    flash[:alert] = t "#{policy_name}.#{exception.query}", scope: 'pundit', default: :default
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Paginable

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[edit update destroy]
  before_action :set_categories, only: %i[index new create edit update]

  # rubocop: disable Metrics/AbcSize, Metrics/MethodLength
  def index
    @archives = Article.group_by_month(:created_at, format: '%B %Y', locale: :en).count

    category = @categories.find { |c| c.name == params[:category] } if params[:category].present?
    month_year = @archives.find { |m| m[0] == params[:month_year] }&.first if params[:month_year].present?

    @highlights = Article.includes(:category, :user)
                         .filter_by_category(category)
                         .filter_by_archive(month_year)
                         .desc_order
                         .first(3)

    highlight_ids = @highlights.pluck(:id).join(',')

    @articles = Article.includes(:category, :user)
                       .without_highlights(highlight_ids)
                       .filter_by_category(category)
                       .filter_by_archive(month_year)
                       .desc_order
                       .page(current_page)
  end

  # rubocop: enable Metrics/AbcSize, Metrics/MethodLength
  def show
    @article = Article.includes(comments: :user).find(params[:id])
    authorize @article
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @article.destroy

    redirect_to root_path, notice: t('.success')
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :category_id)
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end

  def set_categories
    @categories = Category.sorted
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = policy_scope(Category.sorted)
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: t('app.create.success', model: Category.model_name.human) }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: t('app.update.success', model: Category.model_name.human) }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: t('app.destroy.success', model: Category.model_name.human) }
        format.json { head :no_content }
      end
    else
      redirect_to categories_url, alert: @category.errors.messages[:base][0]
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
    authorize @category
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def create
    @article.comments.create(comment_params.to_h.merge!({ user_id: current_user.id }))
    redirect_to article_path(@article), notice: t('app.create.success', model: Comment.model_name.human)
  end

  def destroy
    comment = @article.comments.find(params[:id])
    authorize comment

    comment.destroy
    redirect_to article_path(@article), notice: t('app.destroy.success', model: Comment.model_name.human)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/concerns/paginable.rb
module Paginable
  protected

  def current_page
    (params[:page] || 1).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def month_day_comma_year(value)
    l(value, format: '%B %e, %Y').capitalize
  end

  def month_year(value)
    l(value.to_datetime, format: '%B %Y').capitalize
  end

  def render_if(condition, template, record)
    render template, record if condition
  end

  def sub_masked_email(email)
    email.gsub(/(?<=.{2}).*@.*(?=\S{2})/, '****@****')
  end
end

app/views/articles/_about.html.erb
<div class="p-4 mb-3 bg-light rounded">
  <h4 class="fst-italic"><%= t 'articles.about.title' %></h4>
  <p class="mb-0"><%= t 'articles.about.description' %></p>
</div>

app/views/articles/_archives.html.erb
<div class="p-4">
  <h4 class="fst-italic"><%= t 'articles.archives' %></h4>
  <ol class="list-unstyled mb-0">
    <% archives.each do |month_year, count| %>
      <li>
        <%= link_to "#{month_year(month_year)} (#{count})", articles_path(month_year: month_year),
            class: "p-2 link-secondary #{'filter-active' if month_year == params[:month_year]}" %>
      </li>
    <% end %>
  </ol>
</div>

app/views/articles/_article.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%= article.title %></h2>
  <p class="blog-post-meta">
    <%= render 'article_detail', article: article %>
  </p>

  <p><%= truncate(article.body, length: 150) %></p>

  <p><%= link_to t('articles.continue_reading'), article, class: 'btn btn-link' %></p>

  <%= link_to t('app.button.edit'), edit_article_path(article),
              class: 'btn btn-primary' if policy(article).update? %>

  <%= link_to t('app.button.destroy'), article_path(article),
    method: :delete,
    data: { confirm: t('app.message.confirm_destroy') },
    class: 'btn btn-danger' if policy(article).destroy? %>
</article>

app/views/articles/_article_detail.html.erb
<%= month_day_comma_year(article.created_at) %>  <%= t('app.word.by') %>
<%= sub_masked_email(article.user_email) %> <%= t('app.word.in') %>
<%= article.category_name %>

app/views/articles/_elsewhere.html.erb
<div class="p-4">
  <h4 class="fst-italic"><%= t 'articles.elsewhere' %></h4>
  <ol class="list-unstyled">
    <li><a href="https://github.com/huelton" target="_blank">GitHub</a></li>
    <li><a href="https://twitter.com/hueltonsantos" target="_blank">Twitter</a></li>
  </ol>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, input_html: { rows: 10 } %>
    <%= f.association :category, collection: categories, prompt: t('articles.form.choose_category') %>
  </div>

  <div class="form-action">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to t('app.button.back'), root_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/articles/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 fst-italic"><%= article.title %></h1>
    <p class="lead my-3"><%= truncate(article.body, length: 100) %></p>
    <p class="lead mb-0">
      <%= link_to t('articles.continue_reading'), article, class: 'text-white fw-bold' %>
    </p>
  </div>
</div>

app/views/articles/_medium_featured.html.erb
<div class="col-md-6">
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary">
        <%= article.category_name %>
      </strong>

      <h3 class="mb-0"><%= article.title %></h3>

      <div class="mb-1 text-muted">
        <%= render 'article_detail', article: article %>
      </div>

      <p class="card-text mb-auto">
        <%= truncate(article.body, length: 100)  %>
      </p>

      <%= link_to t('articles.continue_reading'), article, class: 'stretched-link' %>
    </div>

    <div class="col-auto d-none d-lg-block">
      <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

    </div>
  </div>
</div>

app/views/articles/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">
  <%= link_to_next_page articles, t('app.pagination.older'), class: 'btn btn-outline-primary' %>
  <%= link_to_previous_page articles, t('app.pagination.newer'), class: 'btn btn-outline-primary' %>
</nav>

app/views/articles/_right_side.html.erb
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <%= render 'about' %>

    <%= render 'archives', archives: archives %>

    <%= render 'elsewhere' %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1><%= t('app.edit.title', model: Article.model_name.human) %></h1>

<%= render 'form', article: @article, categories: @categories %>

app/views/articles/index.html.erb
<%= render_if @highlights[0].present?, 'longer_featured', article: @highlights[0] %>

<div class="row mb-2">
  <%= render_if @highlights[1].present?, 'medium_featured', article: @highlights[1] %>
  <%= render_if @highlights[2].present?, 'medium_featured', article: @highlights[2] %>
</div>

<div class="row g-5">
  <div class="col-md-8">
    <h3 class="pb-4 mb-4 fst-italic border-bottom">
      <%= t '.subtitle' %>
    </h3>

    <p>
      <%= link_to t('articles.new.title'), new_article_path,
                  { class: 'btn btn-success',
                    'data-bs-toggle': 'tooltip',
                    'data-bs-placement': 'top',
                    title: t('articles.new.title')
                  } if user_signed_in? %>
    </p>

    <%= render @articles %>

    <%= render 'pagination', articles: @articles %>
  </div>

  <%= render 'right_side', archives: @archives %>
</div>

<%= content_for :category_filter do %>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <% @categories.each do |category| %>
        <%= link_to category.name, articles_path(category: category.name),
            class: "p-2 link-secondary #{'filter-active' if category.name.to_s == params[:category]}" %>
      <% end %>
    </nav>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', article: @article, categories: @categories %>

app/views/articles/show.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%= @article.title %></h2>
  <p class="blog-post-meta">
    <%= render 'article_detail', article: @article %>
  </p>

  <p><%= @article.body %></p>

  <%= link_to t('app.button.edit'), edit_article_path(@article),
  class: 'btn btn-primary' if policy(@article).update? %>

  <%= link_to t('app.button.destroy'), article_path(@article),
    method: :delete,
    data: { confirm: t('app.message.confirm_destroy') },
    class: 'btn btn-danger' if policy(@article).destroy? %>

  <%= link_to t('app.button.back'), root_path, class: 'btn btn-secondary' %>

  <h2 class="mt-3"><%= t('.comments') %></h2>
  <%= render @article.comments, article: @article %>

  <h3><%= t('.add_comment') %></h3>
  <% if policy(:comment).create? %>
    <%= render 'comments/form', article: @article %>
  <% else %>
    <%= t('.login_create_comment') %>
  <% end %>
</article>

app/views/categories/_form.html.erb
<%= simple_form_for(category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('app.edit.title', model: Category.model_name.human) %></h1>

<%= render 'form', category: @category %>

<%= link_to t('app.button.back'), categories_path %>

app/views/categories/index.html.erb
<h1><%= t Category.model_name.human(count: 2) %></h1>

<p>
  <%= link_to t('categories.new.title', model: Category.model_name.human), new_category_path,
  class: 'btn btn-primary' if policy(:category).new? %>
</p>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th><%= t Category.human_attribute_name('name') %></th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to t('app.button.edit'), edit_category_path(category) if policy(category).edit? %>
          <%= link_to t('app.button.destroy'), category,
          method: :delete, data: { confirm: t('app.message.confirm_destroy') } if policy(category).destroy? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', category: @category %>

<%= link_to t('app.button.back'), categories_path %>

app/views/comments/_comment.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= month_day_comma_year(comment.created_at) %></h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <%= t 'comments.index.commenter' %>: <%= sub_masked_email(comment.user_email) %>
    </h6>
    <p class="card-text"><%= comment.body %></p>
    <%= link_to t('app.button.destroy'), article_comment_path(article, comment),
      method: :delete,
      data: { confirm: t('app.message.confirm_destroy') },
      class: 'btn btn-danger' if policy(comment).destroy? %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [article, article.comments.build] do |f| %>
  <div class="form-inputs">
    <%= f.input :body, input_html: { rows: 10 } %>
  </div>

  <div class="form-action">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_account_links.html.erb
<% if user_signed_in? %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      <%= sub_masked_email(current_user.email) %>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li>
        <%= link_to t('app.menu.edit_user'), edit_user_registration_path, class: 'dropdown-item' %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <%= link_to t('app.menu.sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </li>
    </ul>
  </div>
<% else %>
  <%= link_to t('app.menu.sign_in'), new_user_session_path, class: 'link-secondary' %>&nbsp;&nbsp;
  <%= link_to t('app.menu.sign_up'), new_user_registration_path, class: 'btn btn-sm btn-outline-secondary' %>
<% end%>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= t 'app.footer.template_info' %>
    <a href="https://getbootstrap.com/">Bootstrap</a>
    <%= t 'app.word.by' %>
    <a href="https://twitter.com/mdo">@hdsantos</a>.
  </p>
  <p>
    <a href="#"><%= t 'app.footer.back_to_top' %></a>
  </p>
</footer>

app/views/layouts/_locale_links.html.erb
<% if I18n.locale == I18n.default_locale %>
  <%= link_to 'English', { locale: :'en' }, class: 'link-secondary' %>
<% else %>
  <%= link_to 'Português', { locale: :'pt-BR' }, class: 'link-secondary' %>
<% end %>

app/views/layouts/_topnavbar.html.erb
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <%= link_to t('app.menu.categories'), categories_path,
                    class: 'link-secondary' if policy(:category).index? %>
      </div>

      <div class="col-4 text-center">
        <%= link_to t('app.title'), root_path, class: 'blog-header-logo text-dark' %>
      </div>

      <div class="col-4 d-flex justify-content-end align-items-center">
        <%= render 'layouts/locale_links' %>
        &nbsp;&nbsp;
        <%= render 'layouts/account_links' %>
      </div>
    </div>
  </header>

  <%= yield :category_filter %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogstrap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/topnavbar' %>

    <main class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>